project:
  type: website

website:
  title: "Gyaltsen1741.github.io"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Courses"
        href: courses.qmd
      - text: "Mini Project 1: Static Maps"
        href: Mini-Project_1_Static_maps.qmd
      - text: "Mini Project 1: Interactive Maps"
        href: Mini-Project_1_Interactive_maps.qmd
      - text: "Mini Project 2"
        href: Mini_Project2.qmd
format:
  html:
    theme: cosmo
    css: styles.css


